apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    name: app
spec:
  type: LoadBalancer
  selector:
    name: app
  ports:
    - port: 80
      protocol: TCP
      name: http
      targetPort: 4000
